/**
 * Demo data. Idempotent: re-running it updates the same accounts and products
 * instead of creating duplicates, so `make seed` is safe at any time.
 *
 * The five products are real GLB files with real animation clips, generated by
 * `pnpm --filter @3dsfera/tools run gen:assets` and committed under
 * prisma/seed-assets. They go through the same upload validation and the same
 * optimization pipeline a supplier's file does — the seeded world is not a
 * special case.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { products, suppliers, type ProductSeed } from './seed-data.js';
import { prisma } from '../src/lib/prisma.js';
import { hashPassword } from '../src/lib/password.js';
import { attachModel, attachPreview, runModelJob } from '../src/modules/products/processing.js';

const DEMO_PASSWORD = 'sfera-demo-2026';

/**
 * Re-runs the optimization pipeline for the demo products even when they
 * already have processed assets. Needed after regenerating the models or
 * changing the pipeline; skipped by default because encoding five models with
 * 4K textures takes minutes.
 *
 *   SEED_REPROCESS=1 pnpm --filter @3dsfera/api run seed
 */
const REPROCESS = process.env['SEED_REPROCESS'] === '1';
const ASSET_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'seed-assets');

async function seedAccounts(): Promise<Map<string, string>> {
  const passwordHash = await hashPassword(DEMO_PASSWORD);
  const supplierIds = new Map<string, string>();

  await prisma.user.upsert({
    where: { email: 'admin@demo.3dsfera.local' },
    update: { role: 'ADMIN', passwordHash },
    create: { email: 'admin@demo.3dsfera.local', passwordHash, role: 'ADMIN', locale: 'ru' },
  });

  await prisma.user.upsert({
    where: { email: 'buyer@demo.3dsfera.local' },
    update: { passwordHash },
    create: { email: 'buyer@demo.3dsfera.local', passwordHash, role: 'BUYER', locale: 'ru' },
  });

  let slot = 1;
  for (const entry of suppliers) {
    const user = await prisma.user.upsert({
      where: { email: entry.email },
      update: { passwordHash, role: 'SUPPLIER' },
      create: { email: entry.email, passwordHash, role: 'SUPPLIER', locale: 'ru' },
    });

    const supplier = await prisma.supplier.upsert({
      where: { userId: user.id },
      update: {
        companyName: entry.companyName,
        legalName: entry.legalName,
        taxId: entry.taxId,
        status: entry.status,
      },
      create: {
        userId: user.id,
        companyName: entry.companyName,
        legalName: entry.legalName,
        taxId: entry.taxId,
        contactEmail: entry.email,
        status: entry.status,
      },
    });

    supplierIds.set(entry.key, supplier.id);

    if (entry.pavilionTitle) {
      await prisma.pavilion.upsert({
        where: { slot },
        update: { supplierId: supplier.id, title: entry.pavilionTitle },
        create: {
          supplierId: supplier.id,
          slot,
          title: entry.pavilionTitle,
          theme: slot % 2 === 0 ? 'DEEP_BLUE' : 'GRAPHITE',
          status: 'PUBLISHED',
          worldPosition: { x: (slot - 1) * 26, y: 0, z: 0, rotationY: 0 },
        },
      });
      slot += 1;
    }
  }

  return supplierIds;
}

async function seedProduct(supplierId: string, seed: ProductSeed): Promise<void> {
  const pavilion = await prisma.pavilion.findFirst({
    where: { supplierId },
    select: { id: true },
  });

  const product = await prisma.product.upsert({
    where: { slug: seed.slug },
    update: {
      title: seed.title,
      description: seed.description,
      category: seed.category,
      priceCents: seed.priceCents,
      stock: seed.stock,
      weightGrams: seed.weightGrams,
      lengthMm: seed.lengthMm,
      widthMm: seed.widthMm,
      heightMm: seed.heightMm,
      status: seed.status,
      pavilionId: pavilion?.id ?? null,
    },
    create: {
      supplierId,
      pavilionId: pavilion?.id ?? null,
      slug: seed.slug,
      title: seed.title,
      description: seed.description,
      category: seed.category,
      priceCents: seed.priceCents,
      currency: 'RUB',
      stock: seed.stock,
      weightGrams: seed.weightGrams,
      lengthMm: seed.lengthMm,
      widthMm: seed.widthMm,
      heightMm: seed.heightMm,
      status: seed.status,
      submittedAt: new Date(),
      ...(seed.status === 'PUBLISHED' ? { publishedAt: new Date() } : {}),
      // Plausible traffic, so the statistics screen is not a wall of zeroes.
      viewCount: 40 + Math.floor(Math.random() * 400),
      orderCount: Math.floor(Math.random() * 12),
    },
    select: { id: true },
  });

  if (REPROCESS) {
    await prisma.productAsset.deleteMany({ where: { productId: product.id } });
    await prisma.modelJob.deleteMany({ where: { productId: product.id } });
  }

  const alreadyProcessed = await prisma.productAsset.findFirst({
    where: { productId: product.id, kind: 'GLB_OPTIMIZED' },
    select: { id: true },
  });

  if (!alreadyProcessed) {
    const bytes = new Uint8Array(readFileSync(path.join(ASSET_DIR, seed.file)));
    const { jobId } = await attachModel(prisma, product.id, bytes, { enqueue: false });
    await runModelJob(jobId);
  }

  // The card photograph, when `make previews` has taken one. Optional on
  // purpose: it needs a browser to render with, and a checkout without one
  // should still seed. Without it the card falls back to its placeholder,
  // which is what every seeded product used to get.
  const photograph = path.join(ASSET_DIR, 'previews', `${path.parse(seed.file).name}.png`);
  const hasPreview = await prisma.productAsset.findFirst({
    where: { productId: product.id, kind: 'PREVIEW' },
    select: { id: true },
  });

  if (!hasPreview && existsSync(photograph)) {
    await attachPreview(prisma, product.id, new Uint8Array(readFileSync(photograph)));
  }

  await prisma.productInteraction.deleteMany({ where: { productId: product.id } });
  await prisma.productInteraction.createMany({
    data: seed.interactions.map((interaction, index) => ({
      productId: product.id,
      type: interaction.type,
      clipName: interaction.clipName ?? null,
      label: interaction.label,
      labelEn: interaction.labelEn,
      order: index,
      loop: interaction.loop ?? false,
    })),
  });
}

async function main(): Promise<void> {
  const supplierIds = await seedAccounts();

  for (const seed of products) {
    const supplierId = supplierIds.get(seed.supplierKey);
    if (!supplierId) throw new Error(`Unknown supplier key "${seed.supplierKey}"`);

    process.stdout.write(`  ${seed.title} … `);
    await seedProduct(supplierId, seed);
    console.log('ok');
  }

  const [pavilions, published, pending, assets] = await Promise.all([
    prisma.pavilion.count(),
    prisma.product.count({ where: { status: 'PUBLISHED' } }),
    prisma.product.count({ where: { status: 'PENDING' } }),
    prisma.productAsset.count(),
  ]);

  console.log('\nseed complete');
  console.log(`  admin:     admin@demo.3dsfera.local / ${DEMO_PASSWORD}`);
  console.log(`  buyer:     buyer@demo.3dsfera.local / ${DEMO_PASSWORD}`);
  for (const entry of suppliers) {
    console.log(`  supplier:  ${entry.email} / ${DEMO_PASSWORD}  (${entry.status})`);
  }
  console.log(`  pavilions: ${pavilions}, published: ${published}, pending: ${pending}`);
  console.log(`  assets:    ${assets} objects in storage`);

  await reportProductsWithoutGeometry();
}

/**
 * Refuses to call a seed successful when it produced a showroom with nothing
 * in it.
 *
 * `runModelJob` catches an optimisation failure, writes FAILED on the job and
 * carries on — which is right for a supplier's upload, because one broken
 * model must not take the request down. For the seed it was quietly fatal: the
 * products existed with titles and prices, none of them had geometry, the
 * world endpoint filters those out, and the street came up empty with no
 * pavilions, no plinths and no vendors on them. The only trace was one
 * `[processing] optimization failed` line scrolled off the top of the log.
 *
 * So the check is here, at the end, where somebody reading the output will see
 * it: which products came out without a model, and the reason their job gave.
 */
async function reportProductsWithoutGeometry(): Promise<void> {
  const products = await prisma.product.findMany({
    select: {
      id: true,
      title: true,
      assets: { where: { kind: 'GLB_OPTIMIZED' }, select: { id: true } },
      modelJobs: {
        orderBy: { createdAt: 'desc' },
        take: 1,
        select: { status: true, error: true, errorCode: true },
      },
    },
  });

  const broken = products.filter((product) => product.assets.length === 0);
  if (broken.length === 0) return;

  console.error(`
${broken.length} of ${products.length} products have no model:`);
  for (const product of broken) {
    const job = product.modelJobs[0];
    const reason = job
      ? `${job.status}${job.errorCode ? ` (${job.errorCode})` : ''}: ${job.error ?? 'no message'}`
      : 'no processing job was ever created';
    console.error(`  ${product.title} — ${reason}`);
  }

  console.error(
    '\nA product without geometry is dropped from the 3D world, so its pavilion\n' +
      'comes up empty — no plinths and no vendor on the frontage. Fix the cause\n' +
      'above and run `make seed` again.',
  );

  process.exitCode = 1;
}

main()
  .catch((error: unknown) => {
    console.error('seed failed:', error);
    process.exitCode = 1;
  })
  .finally(() => {
    void prisma.$disconnect();
  });
