/**
 * Demo data. Idempotent: re-running it updates the same accounts and products
 * instead of creating duplicates, so `make seed` is safe at any time.
 *
 * The five products are real GLB files with real animation clips, generated by
 * `pnpm --filter @3dsfera/tools run gen:assets` and committed under
 * prisma/seed-assets. They go through the same upload validation and the same
 * optimization pipeline a supplier's file does — the seeded world is not a
 * special case.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { InteractionType, ProductCategory } from '@3dsfera/shared';
import { prisma } from '../src/lib/prisma.js';
import { hashPassword } from '../src/lib/password.js';
import { attachModel, runModelJob } from '../src/modules/products/processing.js';

const DEMO_PASSWORD = 'sfera-demo-2026';

/**
 * Re-runs the optimization pipeline for the demo products even when they
 * already have processed assets. Needed after regenerating the models or
 * changing the pipeline; skipped by default because encoding five models with
 * 4K textures takes minutes.
 *
 *   SEED_REPROCESS=1 pnpm --filter @3dsfera/api run seed
 */
const REPROCESS = process.env['SEED_REPROCESS'] === '1';
const ASSET_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'seed-assets');

interface SupplierSeed {
  key: string;
  email: string;
  companyName: string;
  legalName: string;
  taxId: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  pavilionTitle?: string;
}

const suppliers: SupplierSeed[] = [
  {
    key: 'orbita',
    email: 'antenna@demo.3dsfera.local',
    companyName: 'Орбита Связь',
    legalName: 'ООО «Орбита Связь»',
    taxId: '7701234567',
    status: 'APPROVED',
    pavilionTitle: 'Орбита Связь — антенны и связь',
  },
  {
    key: 'domovoy',
    email: 'robotics@demo.3dsfera.local',
    companyName: 'Домовой Роботикс',
    legalName: 'ООО «Домовой Роботикс»',
    taxId: '7809876543',
    status: 'APPROVED',
    pavilionTitle: 'Домовой Роботикс — техника для дома',
  },
  {
    key: 'kronos',
    email: 'furniture@demo.3dsfera.local',
    companyName: 'Мебель Кронос',
    legalName: 'ИП Кронов А. В.',
    taxId: '5405551234',
    status: 'PENDING',
  },
];

interface InteractionSeed {
  type: InteractionType;
  clipName?: string;
  label: string;
  labelEn: string;
  loop?: boolean;
}

interface ProductSeed {
  supplierKey: string;
  slug: string;
  file: string;
  title: string;
  description: string;
  category: ProductCategory;
  priceCents: number;
  stock: number;
  weightGrams: number;
  lengthMm: number;
  widthMm: number;
  heightMm: number;
  status: 'PENDING' | 'PUBLISHED';
  interactions: InteractionSeed[];
}

const products: ProductSeed[] = [
  {
    supplierKey: 'orbita',
    slug: 'antenna-orbita-1-2',
    file: 'antenna-orbita.glb',
    title: 'Антенна спутниковая «Орбита 1.2»',
    description:
      'Офсетная антенна 120 см с моторизованным приводом. Разворачивается одним движением и сама доводит тарелку до спутника. Крепление на стену или мачту, ветровая нагрузка до 30 м/с.',
    category: 'ELECTRONICS',
    priceCents: 1_899_000,
    stock: 25,
    weightGrams: 9_400,
    lengthMm: 1_250,
    widthMm: 700,
    heightMm: 340,
    status: 'PUBLISHED',
    interactions: [
      {
        type: 'GLTF_ANIMATION',
        clipName: 'deploy',
        label: 'Развернуть антенну',
        labelEn: 'Deploy the antenna',
      },
      {
        type: 'GLTF_ANIMATION',
        clipName: 'track_signal',
        label: 'Поймать сигнал',
        labelEn: 'Track the signal',
        loop: true,
      },
      { type: 'GLTF_ANIMATION', clipName: 'fold', label: 'Сложить', labelEn: 'Fold it back' },
    ],
  },
  {
    supplierKey: 'domovoy',
    slug: 'robot-vacuum-domovoy-x2',
    file: 'robot-vacuum.glb',
    title: 'Робот-пылесос «Домовой X2»',
    description:
      'Лидарная навигация, влажная уборка, база самоочистки. Строит карту квартиры за один проход и обходит провода. Ёмкость пылесборника 0,4 л, работа до 180 минут.',
    category: 'HOME_APPLIANCES',
    priceCents: 3_499_000,
    stock: 60,
    weightGrams: 3_800,
    lengthMm: 350,
    widthMm: 350,
    heightMm: 98,
    status: 'PUBLISHED',
    interactions: [
      {
        type: 'GLTF_ANIMATION',
        clipName: 'undock',
        label: 'Съехать с базы',
        labelEn: 'Leave the dock',
      },
      {
        type: 'GLTF_ANIMATION',
        clipName: 'clean_pattern',
        label: 'Запустить уборку',
        labelEn: 'Start cleaning',
        loop: true,
      },
      {
        type: 'GLTF_ANIMATION',
        clipName: 'open_lid',
        label: 'Открыть пылесборник',
        labelEn: 'Open the bin',
      },
    ],
  },
  {
    supplierKey: 'orbita',
    slug: 'inspection-drone-skyeye',
    file: 'inspection-drone.glb',
    title: 'Дрон осмотровый «Skyeye»',
    description:
      'Квадрокоптер для осмотра антенн и кровли. Камера на подвесе, 34 минуты полёта, ветроустойчивость 12 м/с. Складные лучи, кейс в комплекте.',
    category: 'ELECTRONICS',
    priceCents: 8_990_000,
    stock: 8,
    weightGrams: 1_250,
    lengthMm: 480,
    widthMm: 480,
    heightMm: 160,
    status: 'PUBLISHED',
    interactions: [
      {
        type: 'GLTF_ANIMATION',
        clipName: 'rotors_spin',
        label: 'Раскрутить винты',
        labelEn: 'Spin the rotors',
        loop: true,
      },
      { type: 'GLTF_ANIMATION', clipName: 'takeoff', label: 'Взлететь', labelEn: 'Take off' },
      {
        type: 'GLTF_ANIMATION',
        clipName: 'camera_scan',
        label: 'Осмотреть местность',
        labelEn: 'Scan around',
      },
    ],
  },
  {
    supplierKey: 'domovoy',
    slug: 'desk-lamp-meridian',
    file: 'desk-lamp.glb',
    title: 'Настольная лампа «Меридиан»',
    description:
      'Складной светильник с регулируемой цветовой температурой 2700–5600 К. Алюминиевые тяги, утяжелённое основание, поворот плафона на 180°.',
    category: 'LIGHTING',
    priceCents: 649_000,
    stock: 120,
    weightGrams: 1_900,
    lengthMm: 220,
    widthMm: 220,
    heightMm: 520,
    status: 'PUBLISHED',
    interactions: [
      { type: 'GLTF_ANIMATION', clipName: 'fold_open', label: 'Разложить', labelEn: 'Unfold' },
      {
        type: 'GLTF_ANIMATION',
        clipName: 'head_tilt',
        label: 'Наклонить плафон',
        labelEn: 'Tilt the head',
      },
    ],
  },
  {
    supplierKey: 'kronos',
    slug: 'recliner-kronos',
    file: 'recliner-chair.glb',
    title: 'Кресло-реклайнер «Кронос»',
    description:
      'Раскладывается в лежачее положение одним движением. Каркас из бука, наполнитель — холлофайбер высокой плотности, съёмные чехлы.',
    category: 'FURNITURE',
    priceCents: 5_490_000,
    stock: 14,
    weightGrams: 38_000,
    lengthMm: 900,
    widthMm: 950,
    heightMm: 1_060,
    // Its supplier is still under review, so the product waits in the
    // moderation queue — that is what stage 5 will be looking at.
    status: 'PENDING',
    interactions: [
      {
        type: 'GLTF_ANIMATION',
        clipName: 'recline',
        label: 'Разложить кресло',
        labelEn: 'Recline the chair',
      },
      {
        type: 'GLTF_ANIMATION',
        clipName: 'footrest_up',
        label: 'Поднять подножку',
        labelEn: 'Raise the footrest',
      },
      {
        type: 'GLTF_ANIMATION',
        clipName: 'sit_upright',
        label: 'Вернуть в исходное',
        labelEn: 'Sit upright',
      },
    ],
  },
];

async function seedAccounts(): Promise<Map<string, string>> {
  const passwordHash = await hashPassword(DEMO_PASSWORD);
  const supplierIds = new Map<string, string>();

  await prisma.user.upsert({
    where: { email: 'admin@demo.3dsfera.local' },
    update: { role: 'ADMIN', passwordHash },
    create: { email: 'admin@demo.3dsfera.local', passwordHash, role: 'ADMIN', locale: 'ru' },
  });

  await prisma.user.upsert({
    where: { email: 'buyer@demo.3dsfera.local' },
    update: { passwordHash },
    create: { email: 'buyer@demo.3dsfera.local', passwordHash, role: 'BUYER', locale: 'ru' },
  });

  let slot = 1;
  for (const entry of suppliers) {
    const user = await prisma.user.upsert({
      where: { email: entry.email },
      update: { passwordHash, role: 'SUPPLIER' },
      create: { email: entry.email, passwordHash, role: 'SUPPLIER', locale: 'ru' },
    });

    const supplier = await prisma.supplier.upsert({
      where: { userId: user.id },
      update: {
        companyName: entry.companyName,
        legalName: entry.legalName,
        taxId: entry.taxId,
        status: entry.status,
      },
      create: {
        userId: user.id,
        companyName: entry.companyName,
        legalName: entry.legalName,
        taxId: entry.taxId,
        contactEmail: entry.email,
        status: entry.status,
      },
    });

    supplierIds.set(entry.key, supplier.id);

    if (entry.pavilionTitle) {
      await prisma.pavilion.upsert({
        where: { slot },
        update: { supplierId: supplier.id, title: entry.pavilionTitle },
        create: {
          supplierId: supplier.id,
          slot,
          title: entry.pavilionTitle,
          theme: slot % 2 === 0 ? 'DEEP_BLUE' : 'GRAPHITE',
          status: 'PUBLISHED',
          worldPosition: { x: (slot - 1) * 26, y: 0, z: 0, rotationY: 0 },
        },
      });
      slot += 1;
    }
  }

  return supplierIds;
}

async function seedProduct(supplierId: string, seed: ProductSeed): Promise<void> {
  const pavilion = await prisma.pavilion.findFirst({
    where: { supplierId },
    select: { id: true },
  });

  const product = await prisma.product.upsert({
    where: { slug: seed.slug },
    update: {
      title: seed.title,
      description: seed.description,
      category: seed.category,
      priceCents: seed.priceCents,
      stock: seed.stock,
      weightGrams: seed.weightGrams,
      lengthMm: seed.lengthMm,
      widthMm: seed.widthMm,
      heightMm: seed.heightMm,
      status: seed.status,
      pavilionId: pavilion?.id ?? null,
    },
    create: {
      supplierId,
      pavilionId: pavilion?.id ?? null,
      slug: seed.slug,
      title: seed.title,
      description: seed.description,
      category: seed.category,
      priceCents: seed.priceCents,
      currency: 'RUB',
      stock: seed.stock,
      weightGrams: seed.weightGrams,
      lengthMm: seed.lengthMm,
      widthMm: seed.widthMm,
      heightMm: seed.heightMm,
      status: seed.status,
      submittedAt: new Date(),
      ...(seed.status === 'PUBLISHED' ? { publishedAt: new Date() } : {}),
      // Plausible traffic, so the statistics screen is not a wall of zeroes.
      viewCount: 40 + Math.floor(Math.random() * 400),
      orderCount: Math.floor(Math.random() * 12),
    },
    select: { id: true },
  });

  if (REPROCESS) {
    await prisma.productAsset.deleteMany({ where: { productId: product.id } });
    await prisma.modelJob.deleteMany({ where: { productId: product.id } });
  }

  const alreadyProcessed = await prisma.productAsset.findFirst({
    where: { productId: product.id, kind: 'GLB_OPTIMIZED' },
    select: { id: true },
  });

  if (!alreadyProcessed) {
    const bytes = new Uint8Array(readFileSync(path.join(ASSET_DIR, seed.file)));
    const { jobId } = await attachModel(prisma, product.id, bytes, { enqueue: false });
    await runModelJob(jobId);
  }

  await prisma.productInteraction.deleteMany({ where: { productId: product.id } });
  await prisma.productInteraction.createMany({
    data: seed.interactions.map((interaction, index) => ({
      productId: product.id,
      type: interaction.type,
      clipName: interaction.clipName ?? null,
      label: interaction.label,
      labelEn: interaction.labelEn,
      order: index,
      loop: interaction.loop ?? false,
    })),
  });
}

async function main(): Promise<void> {
  const supplierIds = await seedAccounts();

  for (const seed of products) {
    const supplierId = supplierIds.get(seed.supplierKey);
    if (!supplierId) throw new Error(`Unknown supplier key "${seed.supplierKey}"`);

    process.stdout.write(`  ${seed.title} … `);
    await seedProduct(supplierId, seed);
    console.log('ok');
  }

  const [pavilions, published, pending, assets] = await Promise.all([
    prisma.pavilion.count(),
    prisma.product.count({ where: { status: 'PUBLISHED' } }),
    prisma.product.count({ where: { status: 'PENDING' } }),
    prisma.productAsset.count(),
  ]);

  console.log('\nseed complete');
  console.log(`  admin:     admin@demo.3dsfera.local / ${DEMO_PASSWORD}`);
  console.log(`  buyer:     buyer@demo.3dsfera.local / ${DEMO_PASSWORD}`);
  for (const entry of suppliers) {
    console.log(`  supplier:  ${entry.email} / ${DEMO_PASSWORD}  (${entry.status})`);
  }
  console.log(`  pavilions: ${pavilions}, published: ${published}, pending: ${pending}`);
  console.log(`  assets:    ${assets} objects in storage`);
}

main()
  .catch((error: unknown) => {
    console.error('seed failed:', error);
    process.exitCode = 1;
  })
  .finally(() => {
    void prisma.$disconnect();
  });
