/**
 * The two typefaces the interface is set in, served from our own origin.
 *
 *   pnpm --filter @3dsfera/tools run fetch:fonts
 *
 * Not a link to Google. A stylesheet from fonts.googleapis.com is a render
 * block on somebody else's uptime, a third party told about every visitor, and
 * the first thing the desktop shell's content security policy refuses. The
 * files are fetched once, written into `public/fonts`, and the CSS beside them
 * is generated with local paths — so the application looks the same offline as
 * online, and nobody outside is asked who is reading the page.
 *
 * Both are variable fonts under the SIL Open Font License, and both have
 * Cyrillic, which is not optional here: the primary language is Russian and
 * half the beautiful display faces do not cover it.
 *
 * Nothing is committed. A megabyte of woff2 does not belong in git, and this
 * file reproduces it exactly.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, '../../web/public/fonts');

/**
 * Google serves one file per script. Only these four are wanted: Cyrillic
 * because that is the product's language, Latin because half the interface is
 * in it, and the two "ext" ranges because they carry the quotation marks and
 * dashes the copy actually uses.
 */
const SUBSETS = new Set(['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']);

interface Family {
  /** The name in the CSS2 query. */
  query: string;
  /** What `font-family` will say. */
  name: string;
  /** Short, filename-safe. */
  slug: string;
  note: string;
}

export const FONTS: Family[] = [
  {
    query: 'Inter:wght@100..900',
    name: 'Inter',
    slug: 'inter',
    note: 'Everything that is read rather than looked at.',
  },
  {
    query: 'Playfair Display:wght@400..900',
    name: 'Playfair Display',
    slug: 'playfair',
    note: 'Headings and the wordmark. High contrast, and it has Cyrillic.',
  },
];

/**
 * Google decides which format to serve from the user agent it is told about.
 * Claiming a current Chrome gets woff2 with a variable axis; claiming nothing
 * gets a pile of static TrueType.
 */
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

interface Face {
  subset: string;
  style: string;
  weight: string;
  url: string;
  unicodeRange: string;
}

/**
 * Pulls the faces out of a CSS2 response.
 *
 * The subset name is only ever in a comment above its block, which is why this
 * is a line walk rather than one expression: there is no way to ask the API
 * which range is which.
 */
function parseFaces(css: string): Face[] {
  const faces: Face[] = [];
  let subset = '';
  let current: Partial<Face> = {};

  for (const raw of css.split('\n')) {
    const line = raw.trim();

    const comment = /^\/\*\s*(.+?)\s*\*\/$/.exec(line);
    if (comment?.[1]) {
      subset = comment[1];
      continue;
    }

    if (line === '@font-face {') {
      current = { subset };
      continue;
    }

    const style = /^font-style:\s*(.+);$/.exec(line);
    if (style?.[1]) current.style = style[1];

    const weight = /^font-weight:\s*(.+);$/.exec(line);
    if (weight?.[1]) current.weight = weight[1];

    const src = /url\((https:\/\/[^)]+)\)/.exec(line);
    if (src?.[1]) current.url = src[1];

    const range = /^unicode-range:\s*(.+);$/.exec(line);
    if (range?.[1]) current.unicodeRange = range[1];

    if (line === '}' && current.url && current.unicodeRange) {
      faces.push({
        subset: current.subset ?? '',
        style: current.style ?? 'normal',
        weight: current.weight ?? '400',
        url: current.url,
        unicodeRange: current.unicodeRange,
      });
      current = {};
    }
  }

  return faces;
}

async function main(): Promise<void> {
  await mkdir(OUT, { recursive: true });

  const rules: string[] = [
    '/*',
    ' * Generated by apps/tools/src/fetch-fonts.ts. Do not edit.',
    ' *',
    ' * Served from our own origin so the interface does not depend on a third',
    ' * party being up, does not tell one who is reading, and works offline.',
    ' */',
    '',
  ];

  let bytes = 0;

  for (const family of FONTS) {
    const response = await fetch(
      `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family.query)}&display=swap`,
      { headers: { 'user-agent': UA } },
    );

    if (!response.ok) {
      throw new Error(`Google Fonts: ${response.status} for ${family.query}`);
    }

    const faces = parseFaces(await response.text()).filter((face) => SUBSETS.has(face.subset));
    if (faces.length === 0) throw new Error(`No wanted subsets for ${family.name}`);

    for (const face of faces) {
      const file = `${family.slug}-${face.subset}.woff2`;
      const target = path.join(OUT, file);

      if (!existsSync(target)) {
        const font = await fetch(face.url, { headers: { 'user-agent': UA } });
        if (!font.ok) throw new Error(`${font.status} for ${face.url}`);
        await writeFile(target, new Uint8Array(await font.arrayBuffer()));
      }

      bytes += (await readFile(target)).byteLength;

      rules.push(
        `/* ${family.name} — ${face.subset} */`,
        '@font-face {',
        `  font-family: '${family.name}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${file}') format('woff2');`,
        `  unicode-range: ${face.unicodeRange};`,
        '}',
        '',
      );
    }

    console.log(`  ${family.name.padEnd(18)} ${faces.length} subsets — ${family.note}`);
  }

  await writeFile(path.join(OUT, 'fonts.css'), rules.join('\n'));
  console.log(`\n${(bytes / 1024).toFixed(0)} KB in ${OUT}`);
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  await main();
}
